# WhatATheme
markdown: kramdown

# URL of the Site
url: 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: λ's space
# Description of the Site
description: 乱花渐欲迷人眼，浅草才能没马蹄。
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: blog, math, WhatATheme
# URL for the Image of custom Favicon
favicon-url: /assets/images/masthead_logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/photo_moon_night.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 635176614@qq.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username:  ddongzi
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: λ
# URL for the Image of the Author
author-image: /assets/images/bio_gauss.jpg 
# 60 Words About the Author
author-about: 喜欢代数、拍照
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ddongzi

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
